# Este es un flujo de trabajo básico para ayudarlo a comenzar con Acciones

name: CI

# Controla cuándo se ejecutará el flujo de trabajo.

on:
    #Activa el flujo de trabajo en eventos de solicitud push o pull para el principal
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
    workflow_dispatch: 

# Una ejecución de flujo de trabajo se compone de uno o más trabajos
jobs:
    #Este flujo de trabajo contiene un único trabajo llamado "construir"
    checkout:
    # El tipo de corredor en el que se ejecutará el trabajo.
        runs-on: ubuntu-latest
        
        # Los pasos son una secuencia de tareas que se ejecutan como parte de un trabajo.
        steps:
            # Consulta tu repositorio en $GITHUB_WORKSPACE
            - uses: actions/checkout@v3
    process:
        # El tipo de runner en el que se ejecutará el job.
        runs-on: ubuntu-latest
        steps:
        # Ejecuta un solo comando utilizando el shell de corredores
        - name: Run a one-line script
          run: echo Hello, world!

        # Ejecuta un conjunto de comandos utilizando el shell de corredores
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
